from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class Definition:
    simple: str
    professional: str
    formula: str
    why: str
    caveat: str


DEFINITIONS: dict[str, Definition] = {
    "Revenue": Definition(
        "Money the business generated from its main operations during the period.",
        "Total revenue reported from operating and other revenue lines included in the source statement.",
        "Revenue = reported revenue for the period",
        "It shows the size of the business and whether the top line is expanding or shrinking.",
        "Revenue growth alone does not tell us whether the company is becoming more profitable or generating more cash.",
    ),
    "Revenue Growth": Definition(
        "How much revenue changed compared with the previous period.",
        "Year-over-year percentage change in reported revenue.",
        "(Current Revenue − Previous Revenue) / Previous Revenue × 100",
        "It helps separate expansion from stagnation or contraction.",
        "Strong growth can still come with weaker margins or poor cash conversion.",
    ),
    "Gross Profit": Definition(
        "Revenue left after direct costs of producing the goods or services.",
        "Revenue less cost of revenue / cost of goods sold.",
        "Gross Profit = Revenue − Cost of Revenue",
        "It shows the economics of the product or service before operating overheads.",
        "Different industries have very different normal gross margins.",
    ),
    "Gross Margin": Definition(
        "The percentage of revenue left after direct costs.",
        "Gross profit expressed as a percentage of revenue.",
        "Gross Profit / Revenue × 100",
        "It helps show pricing power, product mix and direct-cost pressure.",
        "An improving margin can come from mix changes as well as genuine operating improvement.",
    ),
    "Operating Profit": Definition(
        "Profit left after the normal costs of running the business but before financing and tax.",
        "Operating income / EBIT reported or derived from the income statement.",
        "Operating Profit = Revenue − Operating Costs",
        "It shows whether the core business is producing profit before financing effects.",
        "The exact line items included can differ across companies and data providers.",
    ),
    "Operating Margin": Definition(
        "How much operating profit the company keeps from each ₹100 of revenue.",
        "Operating profit as a percentage of revenue.",
        "Operating Profit / Revenue × 100",
        "It helps reveal whether growth is translating into better operating economics.",
        "A small margin change can have a large effect on profits when revenue is very large.",
    ),
    "Net Profit": Definition(
        "The bottom-line profit left after expenses, interest and tax.",
        "Net income attributable to the reported period.",
        "Net Profit = Profit after all reported expenses and taxes",
        "It is the accounting profit ultimately available to equity holders, subject to the company's presentation.",
        "Net profit can differ from cash generation because of non-cash items and working-capital movements.",
    ),
    "Net Margin": Definition(
        "How much final profit the company keeps from each ₹100 of revenue.",
        "Net income divided by revenue.",
        "Net Profit / Revenue × 100",
        "It connects the top line with the final bottom line.",
        "A one-year margin can be distorted by unusual income or expenses.",
    ),
    "EPS": Definition(
        "Profit attributable to each share.",
        "Earnings per share based on reported or derived net income and share count.",
        "EPS = Net Income attributable to equity holders / weighted average shares",
        "Investors often use EPS as the earnings base behind per-share valuation ratios such as P/E.",
        "Share-count changes can alter EPS even when total profit changes differently.",
    ),
    "EPS Growth": Definition(
        "How quickly profit per share changed compared with the previous period.",
        "Period-over-period percentage change in EPS.",
        "(Current EPS − Previous EPS) / Previous EPS × 100",
        "It shows whether earnings are growing on a per-share basis.",
        "EPS can grow faster than total profit because the share count may change.",
    ),
    "ROE": Definition(
        "Profit generated compared with the shareholders' capital supporting the business.",
        "Return on Equity measures net income relative to average shareholders' equity.",
        "Net Income / Average Shareholders' Equity × 100",
        "It helps assess how efficiently shareholder capital is being used.",
        "Leverage and a small equity base can increase ROE, so read it with debt and ROA.",
    ),
    "ROA": Definition(
        "Profit generated compared with everything the company owns to run the business.",
        "Return on Assets measures net income relative to average total assets.",
        "Net Income / Average Total Assets × 100",
        "It helps compare the earning power of the asset base.",
        "Asset-heavy and asset-light industries naturally have different ROA profiles.",
    ),
    "ROCE": Definition(
        "Operating return generated on the capital committed to the business.",
        "Return on Capital Employed measures EBIT relative to capital employed.",
        "EBIT / Capital Employed × 100",
        "It focuses on operating efficiency and is useful when comparing capital-intensive businesses.",
        "Capital-employed definitions vary slightly; EQUICAFI states the convention it uses.",
    ),
    "Operating Cash Flow": Definition(
        "Cash the business generated from its normal operations before investing in long-term assets.",
        "Net cash generated from operating activities.",
        "Reported operating cash flow",
        "It provides a cash-based view of the operating engine.",
        "A strong one-year figure can be affected by working-capital timing.",
    ),
    "Capital Expenditure": Definition(
        "Cash spent on long-term assets such as equipment, technology or facilities.",
        "Cash outflow for purchases of property, plant, equipment and other capital assets.",
        "Capital Expenditure = cash outflow for capital assets",
        "It matters because the business may need to reinvest cash to maintain or expand capacity.",
        "Source statements sometimes display capex as a negative cash flow; EQUICAFI normalizes it as a positive spending amount.",
    ),
    "Free Cash Flow": Definition(
        "Cash left after the business generates operating cash and pays for capital spending.",
        "Operating cash flow less capital expenditure.",
        "FCF = Operating Cash Flow − Capital Expenditure",
        "It connects accounting profit to cash that remains after reinvestment.",
        "Free cash flow can move sharply because capital expenditure is often lumpy.",
    ),
    "FCF / Net Income": Definition(
        "The share of accounting profit that remains as free cash flow.",
        "Free cash flow divided by net income.",
        "FCF / Net Income × 100",
        "It helps compare accounting profit with post-investment cash generation.",
        "A ratio below 100% is not automatically bad; the reason for the difference matters.",
    ),
    "Operating Cash Flow / Net Income": Definition(
        "How much operating cash was generated for each ₹1 of reported net profit.",
        "Operating cash flow divided by net income.",
        "Operating Cash Flow / Net Income",
        "It helps examine how closely accounting earnings are being converted into operating cash.",
        "Working-capital movements can temporarily push the ratio above or below 1.0x.",
    ),
    "Debt / Equity": Definition(
        "How much debt the company carries relative to shareholders' equity.",
        "Debt-to-equity measures financial leverage using reported debt and equity.",
        "Total Debt / Shareholders' Equity",
        "It provides context about how much of the capital structure comes from borrowing.",
        "A higher ratio is not automatically unsafe; industry economics and cash-flow coverage matter too.",
    ),
    "Interest Coverage": Definition(
        "How many times operating earnings can cover interest expense.",
        "EBIT divided by interest expense.",
        "EBIT / Interest Expense",
        "It shows the earnings cushion available for financing costs.",
        "Coverage can change quickly when earnings or interest expense changes.",
    ),
    "Net Debt / Operating Cash Flow": Definition(
        "A rough view of how many years of current operating cash would equal net debt, ignoring growth and other uses.",
        "Net debt divided by operating cash flow.",
        "Net Debt / Operating Cash Flow",
        "It connects balance-sheet leverage with actual operating cash generation.",
        "It is an analytical ratio, not a literal debt repayment forecast.",
    ),
    "FCF / Debt": Definition(
        "How much free cash flow the business generated compared with its debt.",
        "Free cash flow divided by total debt.",
        "FCF / Debt × 100",
        "It provides a cash-flow view of debt support.",
        "Capital expenditure cycles and debt maturities are not captured by this one ratio.",
    ),
    "Cash / Debt": Definition(
        "How much cash the company holds compared with its total debt.",
        "Cash and equivalents divided by total debt.",
        "Cash / Debt",
        "It shows the immediate cash cushion relative to borrowing.",
        "Cash may not all be freely deployable or located in the same subsidiaries as debt.",
    ),
    "Liquidity Coverage": Definition(
        "Whether current assets are large enough to cover current liabilities on the balance sheet.",
        "Current ratio: current assets divided by current liabilities.",
        "Current Assets / Current Liabilities",
        "It provides a simple short-term liquidity check.",
        "It includes assets that may not be equally easy to turn into cash.",
    ),
    "Quick Liquidity Coverage": Definition(
        "Whether the more liquid current assets can cover current liabilities.",
        "Quick ratio using current assets less inventory divided by current liabilities.",
        "(Current Assets − Inventory) / Current Liabilities",
        "It provides a stricter short-term liquidity view than the current ratio.",
        "Industry-specific working-capital cycles matter a lot when interpreting this ratio.",
    ),
    "P/E": Definition(
        "How much market price is attached to each ₹1 of current earnings per share.",
        "Price-to-Earnings compares share price with earnings per share.",
        "Share Price / EPS",
        "It connects market valuation with current per-share earnings.",
        "P/E can be distorted when earnings are unusually high, unusually low or negative.",
    ),
    "P/B": Definition(
        "How much the market values each ₹1 of book equity per share.",
        "Price-to-Book compares market price with book value per share.",
        "Share Price / Book Value Per Share",
        "It can be useful when reported net assets are economically meaningful.",
        "Book value may not capture the value of brands, software or other intangible assets well.",
    ),
    "P/S": Definition(
        "How much market value is assigned to each ₹1 of revenue.",
        "Price-to-Sales compares market capitalization with revenue.",
        "Market Capitalization / Revenue",
        "It can be useful when profit margins are temporarily low or volatile.",
        "Revenue contains no direct information about profitability.",
    ),
    "EV/EBITDA": Definition(
        "How much enterprise value the market places on each ₹1 of EBITDA.",
        "Enterprise value divided by EBITDA.",
        "EV / EBITDA",
        "It incorporates debt and cash while focusing on operating earnings before some non-cash and financing effects.",
        "EBITDA is not cash flow and can hide capital-expenditure needs.",
    ),
    "EV/Sales": Definition(
        "How much enterprise value is assigned to each ₹1 of revenue.",
        "Enterprise value divided by revenue.",
        "EV / Revenue",
        "It compares enterprise value with top-line scale.",
        "It does not show whether revenue converts into profit or cash.",
    ),
    "Earnings Yield": Definition(
        "The earnings-per-share return embedded in the current share price.",
        "Earnings yield is the inverse of P/E when EPS is positive.",
        "EPS / Share Price × 100",
        "It expresses the same basic relationship as P/E in percentage form.",
        "It is based on current earnings, not guaranteed future earnings.",
    ),
    "FCF Yield": Definition(
        "Free cash flow generated relative to the company's market value.",
        "Free cash flow divided by market capitalization.",
        "FCF / Market Capitalization × 100",
        "It links cash generation to the equity valuation.",
        "FCF can vary sharply with investment cycles.",
    ),
    "Dividend Yield": Definition(
        "Cash dividends generated relative to the share price.",
        "Annual dividend per share divided by share price.",
        "Dividend Per Share / Share Price × 100",
        "It shows the cash distribution rate implied by the latest dividend data.",
        "Dividend history does not guarantee future dividends.",
    ),
    "Maximum Drawdown": Definition(
        "The largest peak-to-trough fall experienced in the observed price series.",
        "Maximum percentage decline from a running peak to a later trough.",
        "min((Price / Running Peak) − 1) × 100",
        "It describes the severity of historical downside in the selected sample.",
        "A historical drawdown is descriptive and does not forecast the next decline.",
    ),
    "Annualized Volatility": Definition(
        "How widely daily returns moved around their average, scaled to a yearly measure.",
        "Standard deviation of daily returns multiplied by the square root of 252.",
        "Std(Daily Returns) × √252",
        "It describes the historical variability of the share price.",
        "Higher volatility is not automatically better or worse; it means a wider range of observed price moves.",
    ),
    "Downside Volatility": Definition(
        "How much the negative daily returns varied in the observed sample.",
        "Annualized standard deviation of negative daily returns.",
        "Std(Negative Daily Returns) × √252",
        "It focuses specifically on variability on down days.",
        "It depends on the chosen historical window and the number of down observations.",
    ),
    "Worst Daily Return": Definition(
        "The largest single-day percentage loss observed in the sample.",
        "Minimum daily percentage return.",
        "min(Daily Returns) × 100",
        "It gives a concrete example of the worst one-session decline in the selected history.",
        "One extreme day does not describe the entire return distribution.",
    ),
    "Positive Session Rate": Definition(
        "The percentage of observed trading sessions that ended with a positive daily return.",
        "Fraction of positive daily returns in the sample.",
        "Positive Daily Returns / Total Daily Returns × 100",
        "It gives context on how often the stock rose from one session to the next.",
        "It says nothing by itself about the size of gains versus losses.",
    ),
    "52 Week High": Definition(
        "Highest observed closing price in the trailing one-year window.",
        "Maximum closing price over roughly 252 trading sessions.",
        "max(Closing Price over window)",
        "It provides a reference point for recent market range.",
        "The exact window can vary with available trading history.",
    ),
    "52 Week Low": Definition(
        "Lowest observed closing price in the trailing one-year window.",
        "Minimum closing price over roughly 252 trading sessions.",
        "min(Closing Price over window)",
        "It provides a lower reference point for recent market range.",
        "The exact window can vary with available trading history.",
    ),
    "Distance from 52 Week High": Definition(
        "How far the current price is below the recent one-year high.",
        "Percentage distance between current price and trailing 52-week high.",
        "(Current Price / 52W High − 1) × 100",
        "It places today's price inside its recent trading range.",
        "Being far below a prior high does not by itself imply recovery potential.",
    ),
    "Distance from 52 Week Low": Definition(
        "How far the current price is above the recent one-year low.",
        "Percentage distance between current price and trailing 52-week low.",
        "(Current Price / 52W Low − 1) × 100",
        "It shows where the current price sits relative to the recent low.",
        "Distance from a low is descriptive rather than predictive.",
    ),
    "SMA 20": Definition(
        "The average closing price over the last 20 trading sessions.",
        "20-session simple moving average.",
        "Sum of last 20 closes / 20",
        "It smooths short-term price noise to make recent trend direction easier to inspect.",
        "Moving averages lag price movements because they use past data.",
    ),
    "SMA 50": Definition(
        "The average closing price over the last 50 trading sessions.",
        "50-session simple moving average.",
        "Sum of last 50 closes / 50",
        "It provides a medium-term trend reference.",
        "It is backward-looking and can change slowly after a sharp move.",
    ),
    "EMA 20": Definition(
        "A 20-session average that gives more weight to recent prices.",
        "20-session exponential moving average.",
        "EMA using standard smoothing factor 2/(20+1)",
        "It responds more quickly than the comparable simple moving average.",
        "It is still based on historical prices and can produce false trend signals.",
    ),
    "RSI 14": Definition(
        "A momentum measure that compares recent gains with recent losses over 14 sessions.",
        "14-period Relative Strength Index scaled from 0 to 100.",
        "RSI = 100 − 100/(1 + Average Gain / Average Loss)",
        "It helps describe whether recent price momentum has been relatively strong or weak.",
        "Extreme RSI readings do not guarantee a reversal or future price direction.",
    ),
}


def metric_template(name: str) -> Definition:
    return DEFINITIONS.get(
        name,
        Definition(
            "A financial or market measure calculated from the supplied data.",
            "A structured metric calculated from the available source fields.",
            "See the calculation logic used by EQUICAFI.",
            "It is useful when interpreted together with related metrics.",
            "Do not treat a single metric as a complete company assessment.",
        ),
    )
